### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'mc.l mc.d.d()' on a null object reference

### ISSUE THREAD

**Issue by tdammy92** [pusher/pusher-websocket-react-native#112]
Getting this crash report on production,  please i need help with this. 

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'mc.l mc.d.d()' on a null object reference
       at com.pusherwebsocketreactnative.PusherWebsocketReactNativeModule.onUsersInformationReceived(:171)
       at com.pusher.client.channel.impl.PresenceChannelImpl.handleSubscriptionSuccessfulMessage(PresenceChannelImpl.java:104)
       at com.pusher.client.channel.impl.PresenceChannelImpl.handleEvent(PresenceChannelImpl.java:63)
       at com.pusher.client.channel.impl.ChannelManager.handleEvent(ChannelManager.java:16)
       at com.pusher.client.Pusher.handleEvent(Pusher.java:7)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:33)
       at com.pusher.client.connection.websocket.WebSocketConnection.lambda$onMessage$5(WebSocketConnection.java:4)
       at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
       
     `
     
  Device details
  react-native: "0.69.7",
  @pusher/pusher-websocket-react-native: 1.2.2
 Android 13,
Model:Pixel 6a

**Comment by benw-pusher** [comment]
We've released a couple of new versions recently that might help with this issue - are you able to update and let us know if you still get this issue?

**Comment by tdammy92** [comment]
@benw-pusher  thank you for your response,  i think the issue has been resolved, not seen that since the last 1.2.2 update.
