### ISSUE TITLE
PusherWebsocketReactNativeModule.onAuthorizer NullPointerException

### ISSUE THREAD

**Issue by leofolive** [pusher/pusher-websocket-react-native#154]
I'm experiencing an issue related to this library. I've had 421 crashes.

```

Fatal Exception: java.lang.NullPointerException:
       at com.pusherwebsocketreactnative.PusherWebsocketReactNativeModule.onAuthorizer(PusherWebsocketReactNativeModule.kt:158)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:1000)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:242)
       at android.os.Looper.loop(Looper.java:362)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)

```

**Comment by DenisPostnikov** [comment]
+1 on Android
<img width="748" alt="Screenshot 2024-11-07 at 20 08 04" src="https://github.com/user-attachments/assets/a305af9f-40b1-450f-84b1-05c2096c33db">

**Comment by Ahmad-AbdElKader** [comment]
I'm also seeing reported crashes with same error, did anyone manage to fix the problem?
