### ISSUE TITLE
Android App Crashes when when re-subscribing

### ISSUE THREAD

**Issue by devteam-technolabs** [pusher/pusher-websocket-react-native#57]
When The pusher try to re-subcribe the same channel the app crashes

using Latest version of the sdk (v1.1.1)

![Screenshot_1669705972](https://user-images.githubusercontent.com/75498565/204466190-46d9d50d-bc12-4fda-adb4-15c7a555742e.png)

**Comment by kevintsangg** [comment]
#51

**Comment by devteam-technolabs** [comment]
It started coming in old version as well, I thought to revert back to v1.0.2 but I am facing the same crash in older version too.

**Comment by kevintsangg** [comment]
I found a solution to solve this problem by calling the init() method **ONLY ONCE**, and you can still call the _connect()_ or _subscribe()_ method multiple times

What I did was calling the init() method at the very top layer of the application, in my case App.tsx, which it will not re-render at all.

**Comment by devteam-technolabs** [comment]
> I found a solution to solve this problem by calling the init() method **ONLY ONCE**, and you can still call the _connect()_ or _subscribe()_ method multiple times
> 
> What I did was calling the init() method at the very top layer of the application, in my case App.tsx, which it will not re-render at all.

Thanks @kevintsangg . It did the trick

**Comment by benw-pusher** [comment]
Are you able to test this with the latest version, we have changed the behaviour when init is invoked multiple times and this should help with this  behaviour.

**Comment by Vitor-Vilela** [comment]
Is this issue fixed yet? I'm facing a similar problem on my implementation on some Android devices, mainly android 11 and 10, already made sure to call the init() method only once by controlling the call with a boolean state that changes after the the connection is successful. The error is preventing some users to open the aplication, since we call pusher in a context that wraps the main activity screens. I'm already using version 1.2.1 of the sdk, running on react-native 0.67.5 and couldn't reproduce the error on a simulator.

`Fatal Exception: java.lang.NullPointerException:
       at com.pusherwebsocketreactnative.PusherWebsocketReactNativeModule.onAuthorizer(PusherWebsocketReactNativeModule.kt:158)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:223)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by johnsoncwb** [comment]
guys, any idea about how to fix that issue? we are using your library in production and this is affecting a huge part of our users.

**Comment by LFMAKER** [comment]
@benw-pusher Hi, we have been experiencing a critical issue with your library that we paid to use. It is causing significant problems for a large portion of our user base, and we would appreciate your help in resolving the issue as soon as possible. Thank you.

**Comment by benw-pusher** [comment]
There are a few reporters of the issue here - this could help us identify the cause of the issue. Could you each share the version of the library in use (assuming the latest) and the onAuthorizer implementation for your app? 
Attempting to replicate this hasn't been successful so this information will help us focus replication efforts.

**Comment by Vitor-Vilela** [comment]
@benw-pusher, in our project we are using react-native 0.67.5 and pusher 1.2.1
Here is the three main functions we use:

Init
```
  const initializePusher = async (channelName, token) => {
    await pusher.init({
      apiKey: CustomApiKey, //removed for security reasons
      cluster: 'us2',
      onAuthorizer: async (channel_name, socket_id) => {
        try {
          const response = await axios.post(
            `CustomUrl`, //removed for security reasons
            `socket_id=${socket_id}&channel_name=${channel_name}`,
            {
              headers: {
                ourCustomHeaders, //removed for security reasons
              },
            },
          );

          return response.data;
        } catch (error) {
          return { auth: 'error on authentication' };
        }
      },
      onSubscriptionSucceeded: (name, data) => {
        setIsSubscribed(true);
      },
    });

    setInitialized(true);

    await pusher.connect();

    await subscribePusher(channelName);
  };
  ```
  Subscription
  ```
  const subscribePusher = async (channelName: string) => {
    await pusher
      .subscribe({
        channelName,
        onEvent: event => {
          switch (event.eventName) {
            case 'new-message':
              const { message } = JSON.parse(event.data);

              const newMessage: MessageType = {
                message,
                from: 'attendant',
                date: Date.now(),
                sent: true,
              };
              dispatch(ChatActions.addMessage(newMessage));
              break;
            case 'terminate':
              setShowCsatModal(true);
              break;
          }
        },
      })
      .catch(error => {
        Sentry.Native.withScope(scope => {
          scope.setTag('Chat', 'Connection');
          scope.setFingerprint(['chat-screen-pusher-subscribe']);
          scope.setLevel(Sentry.Native.Severity.Error);
          scope.setContext('data', {
            error,
          });
          Sentry.Native.captureException(
            new Error('Error on subscribing to pusher'),
          );
        });
      });
  };
  ```
  The useEffect that calls them
  ```
  useEffect(() => {
    if (tokenJWT && deviceId && canOpenChat) {
      const channelName = `presence-chat-app-${deviceId}`;

      if (!initialized) {
        initializePusher(channelName, tokenJWT).catch(error => {
          Sentry.Native.withScope(scope => {
            scope.setTag('Chat', 'Connection');
            scope.setFingerprint(['chat-screen-pusher-connect']);
            scope.setLevel(Sentry.Native.Severity.Error);
            scope.setContext('data', {
              error,
            });
            Sentry.Native.captureException(
              new Error('Error on connecting to pusher'),
            );
          });
        });
      } else if (!isSubscribed) {
        subscribePusher(channelName);
      }
    } else if (initialized && deviceId && isSubscribed) {
      pusher
        .unsubscribe({
          channelName: `presence-chat-app-${deviceId}`,
        })
        .then(() => {
          setIsSubscribed(false);
        })
        .catch(error => {
          Sentry.Native.withScope(scope => {
            scope.setTag('Chat', 'Unsubscribe');
            scope.setFingerprint(['chat-screen-pusher-unsubscription']);
            scope.setLevel(Sentry.Native.Severity.Error);
            scope.setContext('data', {
              error,
            });
            Sentry.Native.captureException(
              new Error('Error on unsubscribing from pusher'),
            );
          });
        });
    }
  }, [tokenJWT, deviceId, canOpenChat]);
  ```

**Comment by benw-pusher** [comment]
I haven't been able to replicate this error. Could you explain in a little more detail what causes this behaviour? The original report (who has solved the issue) mentioned it occurred following a resubscribe to a channel.
 @Vitor-Vilela you mention some users are unable to open the app. Does this mean other users _are_ able to open the app?
 @Bayramito are there particular actions that cause the behaviour?

**Comment by hoangtrunnam** [comment]
> 

hi. did you fix it yet? I have the same problem,i get this error both in android and ios. when I log out, I have to delete the token, and when I log back in, the init() function will be called again. if the init() function is not called again, the onAuthorizer function cannot be run

in App.ts: 

`
  const onAuthorizer = async (
    channelName: string,
    socketId: string
  ): Promise<PusherAuthorizerResult> => {
    if (token) {
    
      const url = `${baseURL}/broadcasting/auth`;
      const headers = {
        "Content-Type": "application/json",
        Authorization: token,
      };
      const data = {
        socket_id: socketId,
        channel_name: channelName,
      };
      try {
        const response = await axios.post(url, data, { headers });
        const body = response.data as PusherAuthorizerResult;
        return body;
      } catch (error) {
        console.error("Error:", error.message);
      }
    }
  };

  const initPusher = async () => {
    if (!pusherConnection) {
      const newPusher = await pusher.init({
        apiKey: "xxxxxxxxxxx",
        cluster: "xxxxx",
        onConnectionStateChange,
        onAuthorizer,
      });
      await pusher.connect();
      setPusherConnection(newPusher);
    }
  };

  useEffect(() => {
    initPusher();
    return () => {
      if (pusherConnection) {
        pusher.disconnect();
      }
    };
  }, [token]);
`

**Comment by hoangtrunnam** [comment]
> > I found a solution to solve this problem by calling the init() method **ONLY ONCE**, and you can still call the _connect()_ or _subscribe()_ method multiple times
> > What I did was calling the init() method at the very top layer of the application, in my case App.tsx, which it will not re-render at all.
> 
> Thanks @kevintsangg . It did the trick but it is not working for private channels .

hi. did you fix it yet? I have the same problem with you,i get this error both in android and ios. when I log out, I have to delete the token, and when I log back in, the init() function will be called again. if the init() function is not called again, the onAuthorizer function cannot be run

"@pusher/pusher-websocket-react-native": "^1.2.2",
"react-native": "0.68.2",

![image](https://github.com/pusher/pusher-websocket-react-native/assets/57910461/1d561f62-5d73-4a64-bd1e-78426563dc95)

**Comment by owaisansarii** [comment]
Is there any update on this? I am facing the same issue in out app

**Comment by owaisansarii** [comment]
1. **Remove the package**:
   Run the following command to remove the `@pusher/pusher-websocket-react-native` package from your project:

   ```bash
   yarn remove @pusher/pusher-websocket-react-native
   ```

2. **Add a custom repository**:
   In your `package.json`, add the package with a custom repository URL:

   ```json
   "@pusher/pusher-websocket-react-native": "https://github.com/swaaj/pusher-websocket-react-native.git"
   ```

3. **Modify `node_modules` code**:
   In the `node_modules/@pusher/pusher-websocket-react-native/src/index.tsx` file
   
   ```js
   const PusherWebsocketReactNative = NativeModules.PusherWebsocketReactNative
  ? NativeModules.PusherWebsocketReactNative
  : new Proxy(
      {},
      {
        get() {
          throw new Error(LINKING_ERROR);
        },
      }
    );

EVENT_TYPE {
  ON_AUTHORIZER = 'PusherReactNative:onAuthorizer',
  ON_CONNECTION_STATE_CHANGE = 'PusherReactNative:onConnectionStateChange',
  ON_SUBSCRIPTION_ERROR = 'PusherReactNative:onSubscriptionError',
  ON_EVENT = 'PusherReactNative:onEvent',
  ON_ERROR = 'PusherReactNative:onError',
  ON_MEMBER_ADDED = 'PusherReactNative:onMemberAdded',
  ON_MEMBER_REMOVED = 'PusherReactNative:onMemberRemoved',
}
//Rest of the code ....
   ```
   In the same file 
   
   ```js
   public async connect() {
    return await PusherWebsocketReactNative.connect();
  }

  public async disconnect() {
    return await PusherWebsocketReactNative.disconnect();
  }

  private unsubscribeAllChannels() {
    const channelsCopy = new Map(this.channels);
    channelsCopy.forEach((channel) => {
      console.log('UNSUB ALL ',channel)
      this.unsubscribe({ channelName: channel.channelName });
    });
  }

  private removeAllListeners() {
    this.pusherEventEmitter.removeAllListeners(EVENT_TYPE.ON_AUTHORIZER);
    this.pusherEventEmitter.removeAllListeners(EVENT_TYPE.ON_ERROR);
    this.pusherEventEmitter.removeAllListeners(EVENT_TYPE.ON_EVENT);
    this.pusherEventEmitter.removeAllListeners(EVENT_TYPE.ON_MEMBER_ADDED);
    this.pusherEventEmitter.removeAllListeners(EVENT_TYPE.ON_MEMBER_REMOVED);
  }

  public async resetPusherInstance() {
    this.removeAllListeners();
    this.unsubscribeAllChannels();
  }

  async subscribe(args: {
    channelName: string;
    onSubscriptionSucceeded?: (data: any) => void;
    onSubscriptionError?: (
//Rest of the code
   ```
   

4. **Modify `PusherWebsocketReactNativeModule.kt`**:
   In the `node_modules/@pusher/pusher-websocket-react-native/android/src/main/java/com/pusherwebsocketreactnative/PusherWebsocketReactNativeModule.kt` file

 on line no : 163   
 change 
```kt
authorizerMutex.remove(key)
```
To 
```kt
authorizerMutex!!.remove(key)
```

5. **Create a new build**:
   After making these changes, rebuild your React Native project.

6. **Reset Pusher instance**:
   Call `pusher.resetPusherInstance()` before every `init()` or before logging out and logging in (if you have user authentication method)

**Comment by fbenevides** [comment]
Could you please update to the latest version? [1.3.0](https://github.com/pusher/pusher-websocket-react-native/releases/tag/v1.3.0)
